parameters:
  name: "" # defaults for any parameters that aren't specified
  vmImage: ""


jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
      maxParallel: 2

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'
    - script: pip install -r requirements-test.txt
      displayName: 'Install test dependencies'
    - script: pytest
      displayName: 'Run tests'
