# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 'master'
    hooks:
      - id: bandit

