language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=lint
    - python: 3.7
      env: TOXENV=py37
      sudo: true
      dist: xenial
    - python: 3.8-dev
      env: TOXENV=py38
      dist: xenial
      sudo: true
    - python: pypy
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3
  allow_failures:
    - python: pypy3
    - python: 3.8-dev

install:
  - pip install codecov tox

script:
  - tox --recreate

cache:
  directories:
    - .tox

after_success:
  - codecov -e TOXENV

notifications:
  email: false

deploy:
  provider: pypi
  user: Bruno.Alla
  distributions: bdist_wheel sdist
  on:
    branch: master
    repo: browniebroke/deezer-python
    tags: true
    python: 3.6
  password:
    secure: gPn7phpAJc0WUAueMM4Drz4Uds/oYghLA8qiyG2GyFP5i2HnJiQDd+ZZVaSsLSVdiAubfR8RPBuKAbpZ3+g1RzHIiACNLh96G0q/rthytlPowxLxrI3c4BfjBTZ7qDdg1GzWcddrSAjKLN1v1OswuZZ7/T4YG7mdT8SMrLJq+8s=
