language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
    - "pypy3"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls
# command to run tests
script:
    - python -m coverage run -m unittest discover
after_success:
    - coveralls
