language: python

sudo: false

python:
  - '3.5'

env:
  matrix:
    - TOXENV=docs
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35

install:
  - pip install codecov tox

script:
  - tox -e $TOXENV

after_success:
  - codecov -e TOX_ENV

notifications:
  email: false

deploy:
  provider: pypi
  user: Bruno.Alla
  distributions: bdist_wheel sdist
  on:
    branch: master
    repo: browniebroke/deezer-python
    tags: true
    condition: "$TOXENV = py27"
  password:
    secure: gPn7phpAJc0WUAueMM4Drz4Uds/oYghLA8qiyG2GyFP5i2HnJiQDd+ZZVaSsLSVdiAubfR8RPBuKAbpZ3+g1RzHIiACNLh96G0q/rthytlPowxLxrI3c4BfjBTZ7qDdg1GzWcddrSAjKLN1v1OswuZZ7/T4YG7mdT8SMrLJq+8s=
