environment:

  matrix:

    - PYTHON: "C:\\Python27-x64"
      TOXENV: py27

    - PYTHON: "C:\\Python34-x64"
      TOXENV: py34

    - PYTHON: "C:\\Python35-x64"
      TOXENV: py35

    - PYTHON: "C:\\Python36-x64"
      TOXENV: py36

    - PYTHON: "C:\\Python37-x64"
      TOXENV: py37

init:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: off

install:
  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - pip install -U pip
  # Install tox to run tests
  - pip install tox

test_script:
  # Run the project tests
  - tox
